export const IPC_CHANNELS = {
  WINDOW: {
    MINIMIZE: "window:minimize",
    MAXIMIZE: "window:maximize",
    CLOSE: "window:close",
    TOGGLE_FULLSCREEN: "window:toggle-fullscreen",
    OPEN_DEVTOOLS: "window:open-devtools",
    ON_STATE_CHANGE: "window:on-state-change",
  },
  UPDATE: {
    MESSAGE: "update-message",
    PROGRESS: "update-progress",
    START_CHECK: "start-update-check",
    INIT: "update-init",
    INFO: "update-info",
    DOWNLOAD: "update-download",
    INSTALL_AND_RESTART: "update-install-and-restart",
  },
  SECURE_STORAGE: {
    SET: "secure-storage:set",
    GET: "secure-storage:get",
    DELETE: "secure-storage:delete",
  },
  AUTH: {
    LOGIN: "auth:login",
    REGISTER: "auth:register",
    VERIFY_EMAIL: "auth:verify-email",
    GET_EMAIL_VERIFICATION_STATUS: "auth:get-email-verification-status",
    RESEND_EMAIL_VERIFICATION: "auth:resend-email-verification",
    REGISTER_TEST: "auth:register-test",
    REQUEST_DELETE_CODE: "auth:request-delete-code",
    DELETE_ACCOUNT: "auth:delete-account",
    LOGIN_OFFLINE: "auth:login-offline",
    GET_SESSION: "auth:get-session",
    LOGOUT: "auth:logout",
  },
  ADMIN: {
    GET_USERS: "admin:get-users",
    BAN_USER: "admin:ban-user",
    UNBAN_USER: "admin:unban-user",
    UPDATE_ROLES: "admin:update-roles",
    DELETE_TEST_USER: "admin:delete-test-user",
    GET_ROLES: "admin:get-roles",
    CREATE_ROLE: "admin:create-role",
    UPDATE_ROLE: "admin:update-role",
    GET_STATS: "admin:get-stats",
    GET_NEWS: "admin:get-news",
    CREATE_NEWS: "admin:create-news",
    GET_NEWS_TAGS: "admin:get-news-tags",
    CREATE_NEWS_TAG: "admin:create-news-tag",
    UPDATE_NEWS_TAG: "admin:update-news-tag",
    DELETE_NEWS_TAG: "admin:delete-news-tag",
    UPDATE_NEWS: "admin:update-news",
    DELETE_NEWS: "admin:delete-news",
    GET_CHANGELOG: "admin:get-changelog",
    CREATE_CHANGELOG: "admin:create-changelog",
    UPDATE_CHANGELOG: "admin:update-changelog",
    DELETE_CHANGELOG: "admin:delete-changelog",
  },
  JAVA: {
    CHECK_VERSION: "java:check-version",
    FIND_SYSTEM: "java:find-system",
    SELECT_EXECUTABLE: "java:select-executable",
    DOWNLOAD: "java:download",
    DOWNLOAD_PROGRESS: "java:download-progress",
    GET_INSTALLED: "java:get-installed",
    GET_VERSIONS: "java:get-versions",
    REMOVE: "java:remove",
  },
  SYSTEM: {
    GET_MEMORY: "system:get-memory",
    GET_CPUS: "system:get-cpus",
    LOG_ACTION: "system:log-action",
    OPEN_EXTERNAL: "system:open-external",
    OPEN_GITHUB_ISSUE: "system:open-github-issue",
    SELECT_DIRECTORY: "system:select-directory",
    OPEN_PATH: "system:open-path",
    OPEN_DATA_FOLDER: "system:open-data-folder",
    SETTINGS_UPDATED: "system:settings-updated",
    UI_READY: "system:ui-ready",
    SMOKE_TEST_PASSED: "system:smoke-test-passed",
  },
  LOG: {
    EXPORT_AND_REPORT: "logs:export-and-report",
  },
  APP: {
    GET_VERSION: "app:get-version",
    VERIFY_INTEGRITY: "app:verify-integrity",
    GET_LAST_CRASH_REPORT: "app:get-last-crash-report",
    CLEAR_LAST_CRASH_REPORT: "app:clear-last-crash-report",
  },
  GAME: {
    LAUNCH: "game:launch",
    PROGRESS: "game:progress",
    GET_INSTALLED_VERSIONS: "game:get-installed-versions",
  },
} as const;
