/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated user profile. */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        /** Delete the current account after confirming an email code. */
        delete: operations["AccountController_deleteMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a local account with email, username, and bcrypt-hashed password. */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email or username and password. Returns a short-lived access token and stores the refresh token in an HTTP-only cookie. */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify the current account email with a six-digit code. */
        post: operations["AuthController_verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/verification-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return email verification state and resend cooldown for the current user. */
        get: operations["AuthController_emailVerificationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend the email verification message. Returns remaining cooldown seconds. */
        post: operations["AuthController_resendEmailVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token from the HTTP-only cookie and return a new access token. */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current refresh token and clear the cookie. */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oauth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Google OAuth 2.0 login. */
        get: operations["AuthController_googleOAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oauth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth 2.0 callback. Creates or links the user account and sets the refresh cookie. */
        get: operations["AuthController_googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/link-provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link an OAuth provider to the authenticated account using a provider token. */
        post: operations["AuthController_linkProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/unlink-provider/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink an OAuth provider from the account. */
        delete: operations["AuthController_unlinkProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/email/google/oauth-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Create a Google OAuth authorization URL for Gmail sending. */
        get: operations["GmailOAuthController_createAuthorizationUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/email/google/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return Gmail OAuth sender connection status. */
        get: operations["GmailOAuthController_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/email/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove stored Gmail OAuth sender credentials. */
        delete: operations["GmailOAuthController_disconnect"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/email/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback for Gmail sender setup. */
        get: operations["GmailOAuthController_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/delete-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send an email code to confirm deletion of the current account. */
        post: operations["AccountController_requestAccountDeletionCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a test account, assign the test role, and return the email verification code. */
        post: operations["TestAuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/test-user-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a test user without auth, only if the user has test role. */
        delete: operations["TestUsersController_deleteTestUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public launcher server list with pagination, status filter, and text search. */
        get: operations["ServersController_list"];
        put?: never;
        /** Create a game server entry for the launcher. */
        post: operations["ServersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/admin/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin launcher server list. Can include private entries with includePrivate=true. */
        get: operations["ServersController_adminList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{idOrSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one public server by UUID or slug. */
        get: operations["ServersController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{idOrSlug}/status/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping a server on demand and return the persisted live launcher status. */
        get: operations["ServersController_liveStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a game server entry. */
        delete: operations["ServersController_delete"];
        options?: never;
        head?: never;
        /** Update a game server entry. */
        patch: operations["ServersController_update"];
        trace?: never;
    };
    "/api/servers/{id}/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin override to immediately refresh server status. */
        post: operations["ServersController_ping"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public news listing with pagination, sorting, date filtering, text search, and tag ID filtering. */
        get: operations["NewsController_list"];
        put?: never;
        /** Create a news article. Admin/moderator only. */
        post: operations["NewsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all existing news tags. */
        get: operations["NewsController_listTags"];
        put?: never;
        /** Create a news tag. Admin/moderator only. */
        post: operations["NewsController_createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a news tag. Admin/moderator only. */
        delete: operations["NewsController_deleteTag"];
        options?: never;
        head?: never;
        /** Update a news tag. Admin/moderator only. */
        patch: operations["NewsController_updateTag"];
        trace?: never;
    };
    "/api/news/{idOrSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a news article by UUID or slug. */
        get: operations["NewsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a news article. Admin/moderator only. */
        delete: operations["NewsController_delete"];
        options?: never;
        head?: never;
        /** Edit a news article. Admin/moderator only. */
        patch: operations["NewsController_update"];
        trace?: never;
    };
    "/api/changelog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public launcher changelog with pagination, release-date filters, mandatory flag filter, and sorting. */
        get: operations["ChangelogController_list"];
        put?: never;
        /** Create a changelog entry. Admin/moderator only. */
        post: operations["ChangelogController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changelog/{idOrVersion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a changelog entry by UUID or version. */
        get: operations["ChangelogController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changelog/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a changelog entry. Admin/moderator only. */
        delete: operations["ChangelogController_delete"];
        options?: never;
        head?: never;
        /** Edit a changelog entry. Admin/moderator only. */
        patch: operations["ChangelogController_update"];
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users with pagination, search, role ID filter, permission ID filters, and ban status filter. */
        get: operations["AdminController_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ban a user. Admin/moderator only. */
        post: operations["AdminController_ban"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/unban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unban a user. Admin/moderator only. */
        post: operations["AdminController_unban"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign roles to a user. Admin only. */
        put: operations["AdminController_assignRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List existing roles. Admin only. */
        get: operations["AdminController_roles"];
        put?: never;
        /** Create a new role. Admin only. */
        post: operations["AdminController_createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a role only when no users have it. Admin only. */
        delete: operations["AdminController_deleteRole"];
        options?: never;
        head?: never;
        /** Update an existing role. Admin only. */
        patch: operations["AdminController_updateRole"];
        trace?: never;
    };
    "/api/admin/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List existing client permissions. Admin only. */
        get: operations["AdminController_permissions"];
        put?: never;
        /** Create a new client permission. Admin only. */
        post: operations["AdminController_createPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace all client permissions assigned to a user. Admin only. */
        put: operations["AdminController_assignPermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/permissions/{permissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant one client permission to a user. Admin only. */
        post: operations["AdminController_grantPermission"];
        /** Remove one client permission from a user. Admin only. */
        delete: operations["AdminController_revokePermission"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View system statistics. */
        get: operations["AdminController_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/cors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current CORS host allowlist. Admin only. */
        get: operations["AdminController_corsHosts"];
        /** Replace the CORS host allowlist. Admin only. */
        put: operations["AdminController_updateCorsHosts"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserAccessItemResponseDto: {
            /** @example 15515736-b7f0-4214-a48b-d79dc0b77e9d */
            id: string;
            /** @example admin */
            name: string;
        };
        UserResponseDto: {
            /** @example 06b53cf3-f7f1-44e5-badf-50e01d8e7e83 */
            id: string;
            /** @example player@example.com */
            email: string;
            /** @example HerbCrafter */
            username: string;
            /**
             * @example [
             *       {
             *         "id": "15515736-b7f0-4214-a48b-d79dc0b77e9d",
             *         "name": "admin"
             *       }
             *     ]
             */
            roles: components["schemas"]["UserAccessItemResponseDto"][];
            /**
             * @example [
             *       {
             *         "id": "4f02df80-665e-4f8d-8d1d-229d123d8391",
             *         "name": "start-game"
             *       }
             *     ]
             */
            permissions: components["schemas"]["UserAccessItemResponseDto"][];
            /** @example false */
            emailVerified: boolean;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            emailVerifiedAt?: string;
            /**
             * @description Seconds until the user can request another email verification message.
             * @example 42
             */
            emailVerificationResendAvailableInSeconds: number;
            /** @example false */
            isBanned: boolean;
            /** @example Chargeback abuse */
            banReason?: string;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            createdAt: string;
        };
        RegisterDto: {
            /** @example player@example.com */
            email: string;
            /** @example HerbCrafter */
            username: string;
            /** @example Use-a-long-random-password-42 */
            password: string;
        };
        EmailVerificationStatusDto: {
            /** @example false */
            emailVerified: boolean;
            /** @example 42 */
            resendAvailableInSeconds: number;
            /**
             * @description Whether this response triggered a verification email delivery attempt that succeeded.
             * @example true
             */
            emailSent: boolean;
            /**
             * @description Development-only fallback code. Present only when NODE_ENV=development and Gmail OAuth is not connected.
             * @example 123456
             */
            developmentCode?: string;
        };
        AuthResponseDto: {
            /**
             * @description Short-lived JWT access token for Authorization: Bearer.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /** @example 900 */
            expiresIn: number;
            user: components["schemas"]["UserResponseDto"];
            emailVerification?: components["schemas"]["EmailVerificationStatusDto"];
        };
        LoginDto: {
            /**
             * @description Email address or username.
             * @example player@example.com
             */
            identifier: string;
            /** @example Use-a-long-random-password-42 */
            password: string;
        };
        VerifyEmailDto: {
            /**
             * @description Six-digit verification code sent to the account email.
             * @example 123456
             */
            code: string;
        };
        EmailVerifiedResponseDto: {
            /** @example true */
            success: boolean;
        };
        LogoutResponseDto: {
            /** @example true */
            success: boolean;
        };
        LinkProviderDto: {
            /**
             * @description OAuth provider key. Additional providers can be added by registering another verifier strategy.
             * @example google
             */
            provider: string;
            /**
             * @description Provider ID token. For Google this is verified via oauth2.googleapis.com/tokeninfo.
             * @example eyJhbGciOiJSUzI1NiIsImtpZCI6Ij...
             */
            idToken?: string;
            /**
             * @description Provider access token. For Google this is verified via the userinfo endpoint.
             * @example ya29.a0AfH6SM...
             */
            accessToken?: string;
        };
        LinkProviderResponseDto: {
            /** @example google */
            provider: string;
            /** @example true */
            linked: boolean;
        };
        GmailOAuthUrlResponseDto: {
            /** @example https://accounts.google.com/o/oauth2/v2/auth?client_id=...&scope=... */
            authorizationUrl: string;
        };
        GmailOAuthStatusResponseDto: {
            /** @example true */
            connected: boolean;
            /** @example noreply@example.com */
            senderEmail?: string;
            /** @example 2026-04-25T10:30:00.000Z */
            connectedAt?: string;
            /** @example https://www.googleapis.com/auth/gmail.send */
            scope?: string;
        };
        GmailOAuthDisconnectResponseDto: {
            /** @example true */
            success: boolean;
        };
        GmailOAuthCallbackResponseDto: {
            /** @example true */
            success: boolean;
            /** @example noreply@example.com */
            senderEmail: string;
        };
        AccountDeletionCodeStatusDto: {
            /** @example 42 */
            resendAvailableInSeconds: number;
            /**
             * @description Whether this response triggered an account deletion confirmation email delivery attempt that succeeded.
             * @example true
             */
            emailSent: boolean;
            /**
             * @description Development-only fallback code. Present only when NODE_ENV=development and Gmail OAuth is not connected.
             * @example 123456
             */
            developmentCode?: string;
        };
        TestRegisterResponseDto: {
            /**
             * @description Short-lived JWT access token for Authorization: Bearer.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /** @example 900 */
            expiresIn: number;
            user: components["schemas"]["UserResponseDto"];
            emailVerification?: components["schemas"]["EmailVerificationStatusDto"];
            /**
             * @description Email verification code generated for this test registration.
             * @example 123456
             */
            emailVerificationCode: string;
        };
        TestUserDeleteDto: {
            /** @example 06b53cf3-f7f1-44e5-badf-50e01d8e7e83 */
            userId: string;
        };
        GameServerResponseDto: {
            /** @example b3ab9f57-d124-463d-b1a7-6cbdeaf258a6 */
            id: string;
            /** @example survival */
            slug: string;
            /** @example Survival */
            name: string;
            /** @example mc.example.com */
            ip: string;
            /** @example 25565 */
            port: number;
            /** @example 1.20.4 */
            version: string;
            /** @example Main SMP world with claims and economy. */
            description: string;
            /** @example 42 */
            onlinePlayers: number;
            /** @example 200 */
            maxPlayers: number;
            /** @example data:image/png;base64,... */
            icon?: string;
            /** @example A Minecraft Server */
            motd?: string;
            /**
             * @example online
             * @enum {string}
             */
            status: "online" | "offline";
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            lastPing?: string;
            /** @example true */
            isPublic: boolean;
        };
        CreateGameServerDto: {
            /** @example survival */
            slug: string;
            /** @example Survival */
            name: string;
            /** @example mc.example.com */
            ip: string;
            /** @example 25565 */
            port: number;
            /** @example 1.20.4 */
            version: string;
            /** @example Main SMP world with claims and economy. */
            description: string;
            /** @example https://cdn.example.com/server-icons/survival.png */
            icon?: string;
            /** @example Â§aWelcome to Gerbarium Survival */
            motd?: string;
            /** @example true */
            isPublic?: boolean;
        };
        UpdateGameServerDto: {
            /** @example survival */
            slug?: string;
            /** @example Survival */
            name?: string;
            /** @example mc.example.com */
            ip?: string;
            /** @example 25565 */
            port?: number;
            /** @example 1.20.4 */
            version?: string;
            /** @example Main SMP world with claims and economy. */
            description?: string;
            /** @example https://cdn.example.com/server-icons/survival.png */
            icon?: string;
            /** @example Â§aWelcome to Gerbarium Survival */
            motd?: string;
            /** @example true */
            isPublic?: boolean;
        };
        NewsArticleTagResponseDto: {
            /** @example 2f88f7b9-93b2-4de5-9795-624e1a52b962 */
            id: string;
            /** @example season */
            name: string;
        };
        NewsResponseDto: {
            /** @example 8e536e64-5faa-476e-a402-85cd482af8ec */
            id: string;
            /** @example Season Two Starts Friday */
            title: string;
            /** @example season-two-starts-friday */
            slug: string;
            /** @example The new season opens with... */
            content: string;
            /** @example https://cdn.example.com/news/season-two.jpg */
            image?: string;
            /**
             * @example [
             *       {
             *         "id": "2f88f7b9-93b2-4de5-9795-624e1a52b962",
             *         "name": "season"
             *       }
             *     ]
             */
            tags: components["schemas"]["NewsArticleTagResponseDto"][];
            /** @example 06b53cf3-f7f1-44e5-badf-50e01d8e7e83 */
            authorId: string;
            /** @example AdminUser */
            authorUsername?: string;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            updatedAt: string;
        };
        NewsTagResponseDto: {
            /** @example 2f88f7b9-93b2-4de5-9795-624e1a52b962 */
            id: string;
            /** @example season */
            name: string;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            updatedAt: string;
        };
        NewsTagNameDto: {
            /** @example season */
            name: string;
        };
        CreateNewsDto: {
            /** @example Season Two Starts Friday */
            title: string;
            /** @example season-two-starts-friday */
            slug: string;
            /** @example The new season opens with... */
            content: string;
            /** @example https://cdn.example.com/news/season-two.jpg */
            image?: string;
            /**
             * @description Existing news tag IDs to attach to the article.
             * @example [
             *       "2f88f7b9-93b2-4de5-9795-624e1a52b962",
             *       "f5d490c7-0db8-49f9-9628-00313ed0e694"
             *     ]
             */
            tagIds?: string[];
        };
        UpdateNewsDto: {
            /** @example Season Two Starts Friday */
            title?: string;
            /** @example season-two-starts-friday */
            slug?: string;
            /** @example The new season opens with... */
            content?: string;
            /** @example https://cdn.example.com/news/season-two.jpg */
            image?: string;
            /**
             * @description Existing news tag IDs to attach to the article.
             * @example [
             *       "2f88f7b9-93b2-4de5-9795-624e1a52b962",
             *       "f5d490c7-0db8-49f9-9628-00313ed0e694"
             *     ]
             */
            tagIds?: string[];
        };
        ChangelogResponseDto: {
            /** @example 4d0ea760-e421-49f4-904c-dd44a4ad23dc */
            id: string;
            /** @example 1.4.2 */
            version: string;
            /**
             * Format: date-time
             * @example 2026-04-25
             */
            releaseDate: string;
            /**
             * @example [
             *       "Added server browser",
             *       "Fixed launcher auth refresh"
             *     ]
             */
            changes: unknown[][];
            /** @example https://downloads.example.com/launcher-1.4.2.zip */
            downloadUrl: string;
            /** @example false */
            mandatory: boolean;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            updatedAt: string;
        };
        CreateChangelogDto: {
            /** @example 1.4.2 */
            version: string;
            /**
             * Format: date-time
             * @example 2026-04-25
             */
            releaseDate: string;
            /**
             * @example [
             *       "Added server browser",
             *       "Fixed launcher auth refresh"
             *     ]
             */
            changes: unknown[][];
            /** @example https://downloads.example.com/launcher-1.4.2.zip */
            downloadUrl: string;
            /** @example false */
            mandatory: boolean;
        };
        UpdateChangelogDto: {
            /** @example 1.4.2 */
            version?: string;
            /**
             * Format: date-time
             * @example 2026-04-25
             */
            releaseDate?: string;
            /**
             * @example [
             *       "Added server browser",
             *       "Fixed launcher auth refresh"
             *     ]
             */
            changes?: unknown[][];
            /** @example https://downloads.example.com/launcher-1.4.2.zip */
            downloadUrl?: string;
            /** @example false */
            mandatory?: boolean;
        };
        BanUserDto: {
            /** @example Chargeback abuse */
            reason?: string;
        };
        AssignRolesDto: {
            /**
             * @description Role IDs to assign to the user.
             * @example [
             *       "15515736-b7f0-4214-a48b-d79dc0b77e9d"
             *     ]
             */
            roleIds: unknown[][];
        };
        RoleResponseDto: {
            /** @example 15515736-b7f0-4214-a48b-d79dc0b77e9d */
            id: string;
            /** @example moderator */
            name: string;
            /** @example Can moderate content. */
            description?: string;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            createdAt: string;
        };
        CreateRoleDto: {
            /** @example moderator */
            name: string;
            /** @example Can moderate public content. */
            description?: string;
        };
        UpdateRoleDto: {
            /** @example moderator */
            name?: string;
            /** @example Can moderate public content. */
            description?: string;
        };
        PermissionResponseDto: {
            /** @example 4f02df80-665e-4f8d-8d1d-229d123d8391 */
            id: string;
            /** @example start-game */
            name: string;
            /** @example Allows the launcher to start the game. */
            description?: string;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            createdAt: string;
        };
        CreatePermissionDto: {
            /** @example start-game */
            name: string;
            /** @example Allows the launcher to start the game. */
            description?: string;
        };
        AssignPermissionsDto: {
            /**
             * @description Permission IDs to assign to the user.
             * @example [
             *       "4f02df80-665e-4f8d-8d1d-229d123d8391"
             *     ]
             */
            permissionIds: unknown[][];
        };
        AdminStatsDto: {
            /** @example 1420 */
            userCount: number;
            /** @example 7 */
            bannedUserCount: number;
            /** @example 3 */
            activeServers: number;
            /** @example 56 */
            newsCount: number;
            /** @example 12 */
            changelogCount: number;
        };
        CorsHostsResponseDto: {
            /**
             * @example [
             *       "https://launcher.gerbarium.example",
             *       "localhost:5173"
             *     ]
             */
            hosts: unknown[][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AccountController_deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailVerifiedResponseDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailVerifiedResponseDto"];
                };
            };
        };
    };
    AuthController_emailVerificationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailVerificationStatusDto"];
                };
            };
        };
    };
    AuthController_resendEmailVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailVerificationStatusDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
        };
    };
    AuthController_googleOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_linkProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkProviderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkProviderResponseDto"];
                };
            };
        };
    };
    AuthController_unlinkProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
        };
    };
    GmailOAuthController_createAuthorizationUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmailOAuthUrlResponseDto"];
                };
            };
        };
    };
    GmailOAuthController_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmailOAuthStatusResponseDto"];
                };
            };
        };
    };
    GmailOAuthController_disconnect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmailOAuthDisconnectResponseDto"];
                };
            };
        };
    };
    GmailOAuthController_callback: {
        parameters: {
            query: {
                code: string;
                state: string;
                error: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmailOAuthCallbackResponseDto"];
                };
            };
        };
    };
    AccountController_requestAccountDeletionCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDeletionCodeStatusDto"];
                };
            };
        };
    };
    TestAuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRegisterResponseDto"];
                };
            };
        };
    };
    TestUsersController_deleteTestUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestUserDeleteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
        };
    };
    ServersController_list: {
        parameters: {
            query?: {
                search?: string;
                status?: "online" | "offline";
                /** @description Admin-only flag to include private launcher servers. */
                includePrivate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"][];
                };
            };
        };
    };
    ServersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGameServerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"];
                };
            };
        };
    };
    ServersController_adminList: {
        parameters: {
            query?: {
                search?: string;
                status?: "online" | "offline";
                /** @description Admin-only flag to include private launcher servers. */
                includePrivate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"][];
                };
            };
        };
    };
    ServersController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOrSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"];
                };
            };
        };
    };
    ServersController_liveStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOrSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"];
                };
            };
        };
    };
    ServersController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGameServerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"];
                };
            };
        };
    };
    ServersController_ping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"];
                };
            };
        };
    };
    NewsController_list: {
        parameters: {
            query?: {
                search?: string;
                /** @description Filter by news tag ID. */
                tagId?: string;
                fromDate?: string;
                toDate?: string;
                sortBy?: "createdAt" | "updatedAt" | "title";
                order?: "ASC" | "DESC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponseDto"][];
                };
            };
        };
    };
    NewsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNewsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponseDto"];
                };
            };
        };
    };
    NewsController_listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsTagResponseDto"][];
                };
            };
        };
    };
    NewsController_createTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsTagNameDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsTagResponseDto"];
                };
            };
        };
    };
    NewsController_deleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NewsController_updateTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsTagNameDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsTagResponseDto"];
                };
            };
        };
    };
    NewsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOrSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponseDto"];
                };
            };
        };
    };
    NewsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NewsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNewsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponseDto"];
                };
            };
        };
    };
    ChangelogController_list: {
        parameters: {
            query?: {
                fromDate?: string;
                toDate?: string;
                mandatory?: boolean;
                sortBy?: "releaseDate" | "version" | "createdAt";
                order?: "ASC" | "DESC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangelogResponseDto"][];
                };
            };
        };
    };
    ChangelogController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChangelogDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangelogResponseDto"];
                };
            };
        };
    };
    ChangelogController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOrVersion: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangelogResponseDto"];
                };
            };
        };
    };
    ChangelogController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangelogController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChangelogDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangelogResponseDto"];
                };
            };
        };
    };
    AdminController_users: {
        parameters: {
            query?: {
                /** @description Email or username search. */
                search?: string;
                /** @description Role ID. */
                role?: string;
                /** @description Permission IDs. Can be provided as repeated params or comma-separated values. */
                permissions?: string[];
                banned?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    AdminController_ban: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BanUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AdminController_unban: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AdminController_assignRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRolesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AdminController_roles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"][];
                };
            };
        };
    };
    AdminController_createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"];
                };
            };
        };
    };
    AdminController_deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"];
                };
            };
        };
    };
    AdminController_permissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponseDto"][];
                };
            };
        };
    };
    AdminController_createPermission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePermissionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponseDto"];
                };
            };
        };
    };
    AdminController_assignPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignPermissionsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AdminController_grantPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                permissionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AdminController_revokePermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                permissionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AdminController_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsDto"];
                };
            };
        };
    };
    AdminController_corsHosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorsHostsResponseDto"];
                };
            };
        };
    };
    AdminController_updateCorsHosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @example [
                     *       "*"
                     *     ]
                     */
                    hosts: string[];
                } | string[];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorsHostsResponseDto"];
                };
            };
        };
    };
}

