/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated user profile. */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/minecraft/verification-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Minecraft account linking by resolving the submitted username and creating a verification code. */
        post: operations["UsersController_startMinecraftLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/minecraft/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Minecraft account ownership and store UUID, username, skin, and cape URLs. */
        post: operations["UsersController_confirmMinecraftLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/minecraft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink the authenticated user Minecraft profile. */
        delete: operations["UsersController_unlinkMinecraft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a local account with email, username, and bcrypt-hashed password. */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email or username and password. Returns a short-lived access token and stores the refresh token in an HTTP-only cookie. */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token from the HTTP-only cookie and return a new access token. */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current refresh token and clear the cookie. */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oauth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Google OAuth 2.0 login. */
        get: operations["AuthController_googleOAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oauth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth 2.0 callback. Creates or links the user account and sets the refresh cookie. */
        get: operations["AuthController_googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated account profile. */
        get: operations["AuthController_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/link-provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link an OAuth provider to the authenticated account using a provider token. */
        post: operations["AuthController_linkProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/unlink-provider/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink an OAuth provider from the account. */
        delete: operations["AuthController_unlinkProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public launcher server list with pagination, status filter, and text search. */
        get: operations["ServersController_list"];
        put?: never;
        /** Create a game server entry for the launcher. */
        post: operations["ServersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/admin/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin launcher server list. Can include private entries with includePrivate=true. */
        get: operations["ServersController_adminList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{idOrSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one public server by UUID or slug. */
        get: operations["ServersController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{idOrSlug}/status/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping a server on demand and return the persisted live launcher status. */
        get: operations["ServersController_liveStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a game server entry. */
        delete: operations["ServersController_delete"];
        options?: never;
        head?: never;
        /** Update a game server entry. */
        patch: operations["ServersController_update"];
        trace?: never;
    };
    "/api/servers/{id}/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin override to immediately refresh server status. */
        post: operations["ServersController_ping"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public news listing with pagination, sorting, date filtering, text search, and tag filtering. */
        get: operations["NewsController_list"];
        put?: never;
        /** Create a news article. Admin/moderator only. */
        post: operations["NewsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/{idOrSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a news article by UUID or slug. */
        get: operations["NewsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a news article. Admin/moderator only. */
        delete: operations["NewsController_delete"];
        options?: never;
        head?: never;
        /** Edit a news article. Admin/moderator only. */
        patch: operations["NewsController_update"];
        trace?: never;
    };
    "/api/changelog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public launcher changelog with pagination, release-date filters, mandatory flag filter, and sorting. */
        get: operations["ChangelogController_list"];
        put?: never;
        /** Create a changelog entry. Admin/moderator only. */
        post: operations["ChangelogController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changelog/{idOrVersion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a changelog entry by UUID or version. */
        get: operations["ChangelogController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changelog/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a changelog entry. Admin/moderator only. */
        delete: operations["ChangelogController_delete"];
        options?: never;
        head?: never;
        /** Edit a changelog entry. Admin/moderator only. */
        patch: operations["ChangelogController_update"];
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users with pagination, search, role filter, and ban status filter. */
        get: operations["AdminController_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ban a user. Admin/moderator only. */
        post: operations["AdminController_ban"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/unban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unban a user. Admin/moderator only. */
        post: operations["AdminController_unban"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign roles to a user. Admin only. */
        put: operations["AdminController_assignRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View system statistics for the Minecraft ecosystem. */
        get: operations["AdminController_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/cors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current CORS host allowlist. Admin only. */
        get: operations["AdminController_corsHosts"];
        /** Replace the CORS host allowlist. Admin only. */
        put: operations["AdminController_updateCorsHosts"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PlayerProfileResponseDto: {
            /** @example 853c80ef-3c37-49fd-aa49-938b674adae6 */
            minecraftUuid?: string;
            /** @example jeb_ */
            minecraftUsername?: string;
            /** @example http://textures.minecraft.net/texture/abc123 */
            skinUrl?: string;
            /** @example http://textures.minecraft.net/texture/def456 */
            capeUrl?: string;
            /**
             * @example verified
             * @enum {string}
             */
            verificationStatus: "unlinked" | "pending" | "verified";
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            verifiedAt?: string;
        };
        UserResponseDto: {
            /** @example 06b53cf3-f7f1-44e5-badf-50e01d8e7e83 */
            id: string;
            /** @example player@example.com */
            email: string;
            /** @example HerbCrafter */
            username: string;
            /**
             * @example [
             *       "user"
             *     ]
             */
            roles: ("user" | "moderator" | "admin")[];
            /** @example false */
            isBanned: boolean;
            /** @example Chargeback abuse */
            banReason?: string;
            playerProfile?: components["schemas"]["PlayerProfileResponseDto"];
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            createdAt: string;
        };
        StartMinecraftLinkDto: {
            /**
             * @description Minecraft Java username. A verification code is generated and stored for this profile.
             * @example HerbCrafter
             */
            minecraftUsername: string;
        };
        MinecraftVerificationResponseDto: {
            /** @example A7K2Q9 */
            verificationCode: string;
            /**
             * @example pending
             * @enum {string}
             */
            verificationStatus: "pending";
        };
        ConfirmMinecraftLinkDto: {
            /**
             * @description Minecraft Java username to resolve through Mojang services.
             * @example HerbCrafter
             */
            minecraftUsername: string;
            /**
             * @description Verification code returned by the start endpoint. In lookup mode the code must match the pending profile; in username_code mode it must also be present in the resolved Minecraft name.
             * @example A7K2Q9
             */
            verificationCode: string;
        };
        RegisterDto: {
            /** @example player@example.com */
            email: string;
            /** @example HerbCrafter */
            username: string;
            /** @example Use-a-long-random-password-42 */
            password: string;
        };
        AuthResponseDto: {
            /**
             * @description Short-lived JWT access token for Authorization: Bearer.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /** @example 900 */
            expiresIn: number;
            user: components["schemas"]["UserResponseDto"];
        };
        LoginDto: {
            /**
             * @description Email address or username.
             * @example player@example.com
             */
            identifier: string;
            /** @example Use-a-long-random-password-42 */
            password: string;
        };
        LogoutResponseDto: {
            /** @example true */
            success: boolean;
        };
        LinkProviderDto: {
            /**
             * @description OAuth provider key. Additional providers can be added by registering another verifier strategy.
             * @example google
             */
            provider: string;
            /**
             * @description Provider ID token. For Google this is verified via oauth2.googleapis.com/tokeninfo.
             * @example eyJhbGciOiJSUzI1NiIsImtpZCI6Ij...
             */
            idToken?: string;
            /**
             * @description Provider access token. For Google this is verified via the userinfo endpoint.
             * @example ya29.a0AfH6SM...
             */
            accessToken?: string;
        };
        LinkProviderResponseDto: {
            /** @example google */
            provider: string;
            /** @example true */
            linked: boolean;
        };
        GameServerResponseDto: {
            /** @example b3ab9f57-d124-463d-b1a7-6cbdeaf258a6 */
            id: string;
            /** @example survival */
            slug: string;
            /** @example Survival */
            name: string;
            /** @example mc.example.com */
            ip: string;
            /** @example 25565 */
            port: number;
            /** @example 1.20.4 */
            version: string;
            /** @example Main SMP world with claims and economy. */
            description: string;
            /** @example 42 */
            onlinePlayers: number;
            /** @example 200 */
            maxPlayers: number;
            /** @example data:image/png;base64,... */
            icon?: string;
            /** @example A Minecraft Server */
            motd?: string;
            /**
             * @example online
             * @enum {string}
             */
            status: "online" | "offline";
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            lastPing?: string;
            /** @example true */
            isPublic: boolean;
        };
        CreateGameServerDto: {
            /** @example survival */
            slug: string;
            /** @example Survival */
            name: string;
            /** @example mc.example.com */
            ip: string;
            /** @example 25565 */
            port: number;
            /** @example 1.20.4 */
            version: string;
            /** @example Main SMP world with claims and economy. */
            description: string;
            /** @example https://cdn.example.com/server-icons/survival.png */
            icon?: string;
            /** @example §aWelcome to Gerbarium Survival */
            motd?: string;
            /** @example true */
            isPublic?: boolean;
        };
        UpdateGameServerDto: {
            /** @example survival */
            slug?: string;
            /** @example Survival */
            name?: string;
            /** @example mc.example.com */
            ip?: string;
            /** @example 25565 */
            port?: number;
            /** @example 1.20.4 */
            version?: string;
            /** @example Main SMP world with claims and economy. */
            description?: string;
            /** @example https://cdn.example.com/server-icons/survival.png */
            icon?: string;
            /** @example §aWelcome to Gerbarium Survival */
            motd?: string;
            /** @example true */
            isPublic?: boolean;
        };
        NewsResponseDto: {
            /** @example 8e536e64-5faa-476e-a402-85cd482af8ec */
            id: string;
            /** @example Season Two Starts Friday */
            title: string;
            /** @example season-two-starts-friday */
            slug: string;
            /** @example The new season opens with... */
            content: string;
            /** @example https://cdn.example.com/news/season-two.jpg */
            image?: string;
            /**
             * @example [
             *       "season",
             *       "survival"
             *     ]
             */
            tags: unknown[][];
            /** @example 06b53cf3-f7f1-44e5-badf-50e01d8e7e83 */
            authorId: string;
            /** @example AdminUser */
            authorUsername?: string;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            updatedAt: string;
        };
        CreateNewsDto: {
            /** @example Season Two Starts Friday */
            title: string;
            /** @example season-two-starts-friday */
            slug: string;
            /** @example The new season opens with... */
            content: string;
            /** @example https://cdn.example.com/news/season-two.jpg */
            image?: string;
            /**
             * @example [
             *       "season",
             *       "survival"
             *     ]
             */
            tags?: unknown[][];
        };
        UpdateNewsDto: {
            /** @example Season Two Starts Friday */
            title?: string;
            /** @example season-two-starts-friday */
            slug?: string;
            /** @example The new season opens with... */
            content?: string;
            /** @example https://cdn.example.com/news/season-two.jpg */
            image?: string;
            /**
             * @example [
             *       "season",
             *       "survival"
             *     ]
             */
            tags?: unknown[][];
        };
        ChangelogResponseDto: {
            /** @example 4d0ea760-e421-49f4-904c-dd44a4ad23dc */
            id: string;
            /** @example 1.4.2 */
            version: string;
            /**
             * Format: date-time
             * @example 2026-04-25
             */
            releaseDate: string;
            /**
             * @example [
             *       "Added server browser",
             *       "Fixed launcher auth refresh"
             *     ]
             */
            changes: unknown[][];
            /** @example https://downloads.example.com/launcher-1.4.2.zip */
            downloadUrl: string;
            /** @example false */
            mandatory: boolean;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-04-25T10:30:00.000Z
             */
            updatedAt: string;
        };
        CreateChangelogDto: {
            /** @example 1.4.2 */
            version: string;
            /**
             * Format: date-time
             * @example 2026-04-25
             */
            releaseDate: string;
            /**
             * @example [
             *       "Added server browser",
             *       "Fixed launcher auth refresh"
             *     ]
             */
            changes: unknown[][];
            /** @example https://downloads.example.com/launcher-1.4.2.zip */
            downloadUrl: string;
            /** @example false */
            mandatory: boolean;
        };
        UpdateChangelogDto: {
            /** @example 1.4.2 */
            version?: string;
            /**
             * Format: date-time
             * @example 2026-04-25
             */
            releaseDate?: string;
            /**
             * @example [
             *       "Added server browser",
             *       "Fixed launcher auth refresh"
             *     ]
             */
            changes?: unknown[][];
            /** @example https://downloads.example.com/launcher-1.4.2.zip */
            downloadUrl?: string;
            /** @example false */
            mandatory?: boolean;
        };
        BanUserDto: {
            /** @example Chargeback abuse */
            reason?: string;
        };
        AssignRolesDto: {
            /**
             * @example [
             *       "user",
             *       "moderator"
             *     ]
             */
            roles: ("user" | "moderator" | "admin")[];
        };
        AdminStatsDto: {
            /** @example 1420 */
            userCount: number;
            /** @example 7 */
            bannedUserCount: number;
            /** @example 3 */
            activeServers: number;
            /** @example 56 */
            newsCount: number;
            /** @example 12 */
            changelogCount: number;
        };
        CorsHostsResponseDto: {
            /**
             * @example [
             *       "https://launcher.gerbarium.example",
             *       "localhost:5173"
             *     ]
             */
            hosts: unknown[][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_startMinecraftLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartMinecraftLinkDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinecraftVerificationResponseDto"];
                };
            };
        };
    };
    UsersController_confirmMinecraftLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmMinecraftLinkDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_unlinkMinecraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
        };
    };
    AuthController_googleOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AuthController_linkProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkProviderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkProviderResponseDto"];
                };
            };
        };
    };
    AuthController_unlinkProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
        };
    };
    ServersController_list: {
        parameters: {
            query?: {
                search?: string;
                status?: "online" | "offline";
                /** @description Admin-only flag to include private launcher servers. */
                includePrivate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"][];
                };
            };
        };
    };
    ServersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGameServerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"];
                };
            };
        };
    };
    ServersController_adminList: {
        parameters: {
            query?: {
                search?: string;
                status?: "online" | "offline";
                /** @description Admin-only flag to include private launcher servers. */
                includePrivate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"][];
                };
            };
        };
    };
    ServersController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOrSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"];
                };
            };
        };
    };
    ServersController_liveStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOrSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"];
                };
            };
        };
    };
    ServersController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGameServerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"];
                };
            };
        };
    };
    ServersController_ping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameServerResponseDto"];
                };
            };
        };
    };
    NewsController_list: {
        parameters: {
            query?: {
                search?: string;
                tag?: string;
                fromDate?: string;
                toDate?: string;
                sortBy?: "createdAt" | "updatedAt" | "title";
                order?: "ASC" | "DESC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponseDto"][];
                };
            };
        };
    };
    NewsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNewsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponseDto"];
                };
            };
        };
    };
    NewsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOrSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponseDto"];
                };
            };
        };
    };
    NewsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NewsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNewsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponseDto"];
                };
            };
        };
    };
    ChangelogController_list: {
        parameters: {
            query?: {
                fromDate?: string;
                toDate?: string;
                mandatory?: boolean;
                sortBy?: "releaseDate" | "version" | "createdAt";
                order?: "ASC" | "DESC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangelogResponseDto"][];
                };
            };
        };
    };
    ChangelogController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChangelogDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangelogResponseDto"];
                };
            };
        };
    };
    ChangelogController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOrVersion: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangelogResponseDto"];
                };
            };
        };
    };
    ChangelogController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangelogController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChangelogDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangelogResponseDto"];
                };
            };
        };
    };
    AdminController_users: {
        parameters: {
            query?: {
                /** @description Email or username search. */
                search?: string;
                role?: "user" | "moderator" | "admin";
                banned?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    AdminController_ban: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BanUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AdminController_unban: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AdminController_assignRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRolesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AdminController_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsDto"];
                };
            };
        };
    };
    AdminController_corsHosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorsHostsResponseDto"];
                };
            };
        };
    };
    AdminController_updateCorsHosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @example [
                     *       "*"
                     *     ]
                     */
                    hosts: string[];
                } | string[];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorsHostsResponseDto"];
                };
            };
        };
    };
}
