export const ADMIN_TOASTS = {
  newsCreated: "Новость создана",
  newsUpdated: "Новость обновлена",
  newsDeleted: "Новость удалена",
  newsCreateError: "Не удалось создать новость",
  newsUpdateError: "Не удалось обновить новость",
  newsDeleteError: "Не удалось удалить новость",
  tagCreated: "Тег создан",
  tagUpdated: "Тег обновлен",
  tagDeleted: "Тег удален",
  changelogCreated: "Запись changelog создана",
  changelogUpdated: "Запись changelog обновлена",
  changelogDeleted: "Запись changelog удалена",
  changelogCreateError: "Не удалось создать запись changelog",
  changelogUpdateError: "Не удалось обновить запись changelog",
  changelogDeleteError: "Не удалось удалить запись changelog",
  userBanned: "Пользователь забанен",
  userUnbanned: "Пользователь разбанен",
  rolesUpdated: "Роли пользователя обновлены",
  roleCreated: "Роль создана",
  roleCreateError: "Не удалось создать роль",
};
