export const ADMIN_TOASTS = {
  newsCreated: "News created",
  newsUpdated: "News updated",
  newsDeleted: "News deleted",
  newsCreateError: "Failed to create news",
  newsUpdateError: "Failed to update news",
  newsDeleteError: "Failed to delete news",
  tagCreated: "Tag created",
  tagUpdated: "Tag updated",
  tagDeleted: "Tag deleted",
  changelogCreated: "Changelog entry created",
  changelogUpdated: "Changelog entry updated",
  changelogDeleted: "Changelog entry deleted",
  changelogCreateError: "Failed to create changelog entry",
  changelogUpdateError: "Failed to update changelog entry",
  changelogDeleteError: "Failed to delete changelog entry",
  userBanned: "User banned",
  userUnbanned: "User unbanned",
  rolesUpdated: "User roles updated",
  roleCreated: "Role created",
  roleCreateError: "Failed to create role",
};
