export const ERROR_CODES = {
  JAVA_FOLDER_NOT_FOUND: "ERR_JAVA_FOLDER_NOT_FOUND",
  JAVA_CORRUPTED: "ERR_JAVA_CORRUPTED",
  JAVA_UNSUPPORTED_ARCH: "ERR_JAVA_UNSUPPORTED_ARCH",
  DOWNLOAD_FAILED: "ERR_DOWNLOAD_FAILED"
} as const;