export const ERROR_CODES = {
  // Java
  JAVA_FOLDER_NOT_FOUND: 'ERR_JAVA_FOLDER_NOT_FOUND',
  JAVA_CORRUPTED: 'ERR_JAVA_CORRUPTED',
  JAVA_UNSUPPORTED_ARCH: 'ERR_JAVA_UNSUPPORTED_ARCH',
  JAVA_DOWNLOAD_IN_PROGRESS: 'ERR_JAVA_DOWNLOAD_IN_PROGRESS',
  DOWNLOAD_FAILED: 'ERR_DOWNLOAD_FAILED',

  // Secure Storage
  SECURE_STORAGE_SET_FAILED: 'ERR_SECURE_STORAGE_SET_FAILED',
  SECURE_STORAGE_GET_FAILED: 'ERR_SECURE_STORAGE_GET_FAILED',
  SECURE_STORAGE_DELETE_FAILED: 'ERR_SECURE_STORAGE_DELETE_FAILED',

  // Logs
  LOG_FOLDER_NOT_FOUND: 'ERR_LOG_FOLDER_NOT_FOUND',
  LOG_FOLDER_EMPTY: 'ERR_LOG_FOLDER_EMPTY',
  LOG_EXPORT_FAILED: 'ERR_LOG_EXPORT_FAILED',
} as const;