export const UI_STRINGS = {
  COMMON: {
    VERSION: "Версия",
    ERROR: "Ошибка",
    LOADING: "Загрузка...",
    CANCEL: "Отмена",
    CONFIRM: "Подтвердить",
    SAVE: "Сохранить",
    GB: "ГБ",
  },
  WINDOW_CONTROLS: {
    MINIMIZE: "Свернуть",
    MAXIMIZE: "Развернуть",
    RESTORE: "Восстановить",
    CLOSE: "Закрыть",
  },
  LOGIN: {
    USERNAME_PLACEHOLDER: "Логин",
    PASSWORD_PLACEHOLDER: "Пароль",
    PASSWORD_SHOW: "Показать пароль",
    PASSWORD_HIDE: "Скрыть пароль",
    SUBMIT_BUTTON: "Вход",
    AUTHORIZING: "Авторизация...",
    OFFLINE_MODE: "Оффлайн режим",
    FORGOT_PASSWORD: "Забыли пароль?",
    CREATE_ACCOUNT: "Создать аккаунт",
    FOOTER_TEXT: "Gerbarium Launcher v2.0",
    LOGO_ALT: "Minecraft Gerbarium",
  },
  DASHBOARD: {
    PLAYER_DEFAULT: "Игрок",
    LOGOUT_TOOLTIP: "Выйти",
    SERVER_ONLINE: "ОНЛАЙН",
    SERVER_OFFLINE: "ОФФЛАЙН",
    SERVER_STATUS_ONLINE: "Онлайн",
    SERVER_STATUS_OFFLINE: "Оффлайн",
    VERSIONS_TITLE: "Версии",
    VERSION_INSTALLED: "✓ Установлено",
    VERSION_NOT_INSTALLED: "○ Не установлено",
    SETTINGS_BUTTON: "Настройки",
    NEWS_TITLE: "Новости проекта",
    PLAY_BUTTON: "ИГРАТЬ",
    SELECTED_VERSION_LABEL: "Выбранная версия",
    VERSION_NOT_SELECTED: "Не выбрана",
    READY_TO_PLAY: "✓ Готово к запуску",
    NEEDS_INSTALLATION: "○ Требуется установка",
    VERSION_DISPLAY_LABEL: "Версия:",
    PLAY_ICON: "🎮",
    CANCEL_ICON: "❌",
    SELECT_VERSION_ALERT: "Выберите версию для запуска!",
    SERVER_MOTD: "§b§lGerbarium §8| §aКристальное обновление!",
    PLAYER_ID_LABEL: "ID:",
    PLAYER_ID_UNKNOWN: "???",
    PLAYER_RANK_VIP: "VIP",
    PLAY_ARROW_ICON: "▶",
    TIME_REMAINING_LABEL: "Осталось:",
    MOCK_VERSIONS: [
      { id: "gerbarium-1.2", name: "Gerbarium v1.2" },
      { id: "fabric-1.21", name: "Fabric 1.21" },
      { id: "forge-1.20.1", name: "Forge 1.20.1" },
      { id: "vanilla-1.21.4", name: "Vanilla 1.21.4" },
      { id: "vanilla-42", name: "ТЕСТ РЕЛИЗА 1.0.1" },
    ],
  },
  SETTINGS: {
    TITLE: "Настройки",
    BACK_BUTTON: "← Назад",
    LOGOUT_BUTTON: "Выйти",
    TABS: {
      general: "ОБЩИЕ",
      java: "JAVA",
      profile: "ПРОФИЛЬ",
      support: "ПОДДЕРЖКА",
    },
    GENERAL: {
      TITLE: "Общие настройки",
      LANGUAGE_LABEL: "Язык",
      LANGUAGE_OPTIONS: [
        { value: "ru", label: "Русский" },
        { value: "en", label: "English" },
        { value: "es", label: "Español" },
        { value: "fr", label: "Français" },
        { value: "de", label: "Deutsch" },
      ],
      CLOSE_ON_LAUNCH: "Закрывать лаунчер при запуске игры",
      MINIMIZE_TO_TRAY: "Сворачивать в трей",
      DISCORD_RPC: "Показывать статус в Discord (RPC)",
    },
    JAVA: {
      TITLE: "Настройки Java",
      INSTALLED_VERSIONS: "Установленные версии",
      PATH_LABEL: "Путь к Java",
      PATH_PLACEHOLDER: "C:/Program Files/Java/jdk/bin/java.exe",
      BROWSE_BUTTON: "Выбрать файл",
      RAM_LABEL: "Выделение ОЗУ:",
      JVM_ARGS_LABEL: "Аргументы JVM",
      JVM_ARGS_PLACEHOLDER: "-XX:+UseG1GC -XX:MaxGCPauseMillis=50",
      JVM_ARGS_HELP: "Дополнительные параметры для запуска Java",
      DOWNLOAD_BUTTON: (v: number) => `Скачать Java ${v}`,
      ALREADY_INSTALLED: (v: number) => `Java ${v} уже установлена`,
    },
    PROFILE: {
      TITLE: "Настройки профиля",
      USERNAME_LABEL: "Игрок",
      USERNAME_PLACEHOLDER: "Player",
      SKIN_URL_LABEL: "URL скина",
      SKIN_URL_PLACEHOLDER: "https://example.com/skin.png",
      CAPE_URL_LABEL: "URL плаща",
      CAPE_URL_PLACEHOLDER: "https://example.com/cape.png",
      SKIN_PREVIEW_TITLE: "Предпросмотр скина",
      SKIN_LOADING: "Загрузка...",
      SKIN_NOT_SELECTED: "Скин не выбран",
    },
    ACTIONS: {
      SAVE_BUTTON: "Сохранить",
      SAVING: "Сохранение...",
      RESET_BUTTON: "Сбросить",
    },
    DEBUG: {
      TITLE: "Отладка и Поддержка",
      HELP_TEXT:
        "Если вы столкнулись с проблемой, выгрузите логи и прикрепите их к баг-репорту на GitHub.",
      EXPORT_BUTTON: "Сообщить об ошибке (Экспорт логов)",
      EXPORTING: "Архивация...",
      EXPORT_SUCCESS: (path: string) =>
        `Логи успешно сохранены в:\n${path}\n\nОткроется браузер для создания Issue.`,
      EXPORT_ERROR: (err: string) => `Ошибка при сохранении логов:\n${err}`,
      EXPORT_UNEXPECTED_ERROR:
        "Произошла непредвиденная ошибка при экспорте логов.",
      GITHUB_ISSUES_BUTTON: "Связаться через GitHub Issues",
    },
    RESET_MODAL: {
      TITLE: "Сброс настроек",
      TEXT: "Вы уверены, что хотите сбросить все настройки до значений по умолчанию? Это действие нельзя отменить.",
      CONFIRM: "Сбросить",
      CANCEL: "Отмена",
    },
  },
  UPDATE_SCREEN: {
    SEARCHING: "Поиск обновлений...",
    FOUND: "Найдено новое обновление",
    NONE: "update-not-available",
    DOWNLOADED: "Обновление скачано. Перезагрузка...",
    ERROR_PREFIX: "Ошибка:",
    STARTING_LAUNCHER: "Запуск лаунчера...",
    NOT_REQUIRED: "Обновление не требуется",
    COPYRIGHT: "© 2026 Gerbarium. Radmir Klimau.",
  },
  JAVA_STATUS: {
    EXTRACTING: "Распаковка...",
    DOWNLOADING: "Загрузка: ",
    SEARCHING: "Поиск...",
    VERSION_FOUND: "Найдена версия: ",
    REMOVE_CONFIRM: (v: number) => `Удалить Java ${v}?`,
  },
  DOWNLOAD: {
    IDLE: "Ожидание",
    CHECKING: "Проверка файлов...",
    DOWNLOADING: "Загрузка...",
    INSTALLING: "Установка модов...",
    VERIFYING: "Проверка целостности...",
    COMPLETED: "Завершено",
    CANCELLED: "Отменено",
    CALCULATING: "Расчет...",
  },
  NEWS: {
    CATEGORIES: {
      update: "Обновление",
      event: "Событие",
      community: "Сообщество",
      announcement: "Анонс",
    },
    MOCK: [
      {
        title: "Кристальные мобы: Обновление Гербариум!",
        content:
          "Новое крупное обновление добавляет кристальных мобов, новые биомы и улучшенную систему крафта. Исследуйте новые измерения и сражайтесь с эпическими боссами!",
      },
      {
        title: "Новая система скинов",
        content:
          "Теперь вы можете загружать собственные скины прямо в лаунчере! Поддержка HD текстур и плащей.",
      },
      {
        title: "Турнир сообщества",
        content:
          "Присоединяйтесь к еженедельному турниру! Призовой фонд: 10,000 кристаллов. Регистрация открыта до конца недели.",
      },
    ],
  },
  ADMIN: {
    TITLE: "Панель администратора",
    USERS_MANAGEMENT: "Управление пользователями",
    BACK_BUTTON: "← Назад",
    REFRESH: "Обновить",
    LOADING: "Загрузка...",
    SEARCH_PLACEHOLDER: "Поиск по нику или почте...",
    BANNED_BADGE: "ЗАБАНЕН",
    ID_LABEL: "ID:",
    ROLES_LABEL: "Роли:",
    REASON_LABEL: "Причина:",
    NO_USERS: "Пользователи не найдены.",
    BUTTONS: {
      EDIT_ROLES: "Изменить роли",
      UNBAN: "Разбанить",
      BAN: "Забанить",
    },
    PROMPTS: {
      BAN_REASON_TITLE: (username: string) => `Блокировка ${username}`,
      BAN_REASON_PLACEHOLDER: "Например: Нарушение правил",
      UNBAN_CONFIRM_TITLE: (username: string) => `Разбанить ${username}?`,
      EDIT_ROLES_TITLE: (username: string) => `Роли для ${username}`,
    },
    ROLES: {
      USER: "Игрок",
      MODERATOR: "Модератор",
      ADMIN: "Администратор",
    },
    ERRORS: {
      FETCH_USERS: "Не удалось загрузить список пользователей",
      UPDATE_USER: "Не удалось обновить данные пользователя",
    },
  },

  STORE_ERRORS: {
    SETTINGS_SAVE: "Не удалось сохранить настройки",
    SERVER_STATUS: "Не удалось получить статус сервера",
    NEWS_LOAD: "Не удалось загрузить новости",
    AUTH_LOGIN: "Ошибка входа",
    AUTH_REGISTER: "Registration error",
    AUTH_OFFLINE: "Ошибка оффлайн входа",
    AUTH_EMPTY_FIELDS: "Введите логин и пароль",
    AUTH_EMPTY_USERNAME: "Введите имя пользователя",
  },
} as const;
