export const UI_STRINGS = {
  COMMON: {
    VERSION: "Ð’ÐµÑ€ÑÐ¸Ñ",
    ERROR: "ÐžÑˆÐ¸Ð±ÐºÐ°",
    LOADING: "Ð—Ð°Ð³Ñ€ÑƒÐ·ÐºÐ°...",
    CANCEL: "ÐžÑ‚Ð¼ÐµÐ½Ð°",
    CONFIRM: "ÐŸÐ¾Ð´Ñ‚Ð²ÐµÑ€Ð´Ð¸Ñ‚ÑŒ",
    SAVE: "Ð¡Ð¾Ñ…Ñ€Ð°Ð½Ð¸Ñ‚ÑŒ",
    GB: "Ð“Ð‘",
  },
  WINDOW_CONTROLS: {
    MINIMIZE: "Ð¡Ð²ÐµÑ€Ð½ÑƒÑ‚ÑŒ",
    MAXIMIZE: "Ð Ð°Ð·Ð²ÐµÑ€Ð½ÑƒÑ‚ÑŒ",
    RESTORE: "Ð’Ð¾ÑÑÑ‚Ð°Ð½Ð¾Ð²Ð¸Ñ‚ÑŒ",
    CLOSE: "Ð—Ð°ÐºÑ€Ñ‹Ñ‚ÑŒ",
  },
  LOGIN: {
    USERNAME_PLACEHOLDER: "Ð›Ð¾Ð³Ð¸Ð½",
    PASSWORD_PLACEHOLDER: "ÐŸÐ°Ñ€Ð¾Ð»ÑŒ",
    PASSWORD_SHOW: "ÐŸÐ¾ÐºÐ°Ð·Ð°Ñ‚ÑŒ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ",
    PASSWORD_HIDE: "Ð¡ÐºÑ€Ñ‹Ñ‚ÑŒ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ",
    SUBMIT_BUTTON: "Ð’Ñ…Ð¾Ð´",
    AUTHORIZING: "ÐÐ²Ñ‚Ð¾Ñ€Ð¸Ð·Ð°Ñ†Ð¸Ñ...",
    OFFLINE_MODE: "",
    FORGOT_PASSWORD: "Ð—Ð°Ð±Ñ‹Ð»Ð¸ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ?",
    CREATE_ACCOUNT: "Ð¡Ð¾Ð·Ð´Ð°Ñ‚ÑŒ Ð°ÐºÐºÐ°ÑƒÐ½Ñ‚",
    FOOTER_TEXT: "Gerbarium Launcher v2.0",
    LOGO_ALT: "Minecraft Gerbarium",
  },
  DASHBOARD: {
    PLAYER_DEFAULT: "Ð˜Ð³Ñ€Ð¾Ðº",
    LOGOUT_TOOLTIP: "Ð’Ñ‹Ð¹Ñ‚Ð¸",
    SERVER_ONLINE: "ÐžÐÐ›ÐÐ™Ð",
    SERVER_OFFLINE: "ÐžÐ¤Ð¤Ð›ÐÐ™Ð",
    SERVER_STATUS_ONLINE: "ÐžÐ½Ð»Ð°Ð¹Ð½",
    SERVER_STATUS_OFFLINE: "ÐžÑ„Ñ„Ð»Ð°Ð¹Ð½",
    VERSIONS_TITLE: "Ð’ÐµÑ€ÑÐ¸Ð¸",
    VERSION_INSTALLED: "âœ“ Ð£ÑÑ‚Ð°Ð½Ð¾Ð²Ð»ÐµÐ½Ð¾",
    VERSION_NOT_INSTALLED: "â—‹ ÐÐµ ÑƒÑÑ‚Ð°Ð½Ð¾Ð²Ð»ÐµÐ½Ð¾",
    SETTINGS_BUTTON: "ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸",
    NEWS_TITLE: "ÐÐ¾Ð²Ð¾ÑÑ‚Ð¸ Ð¿Ñ€Ð¾ÐµÐºÑ‚Ð°",
    PLAY_BUTTON: "Ð˜Ð“Ð ÐÐ¢Ð¬",
    SELECTED_VERSION_LABEL: "Ð’Ñ‹Ð±Ñ€Ð°Ð½Ð½Ð°Ñ Ð²ÐµÑ€ÑÐ¸Ñ",
    VERSION_NOT_SELECTED: "ÐÐµ Ð²Ñ‹Ð±Ñ€Ð°Ð½Ð°",
    READY_TO_PLAY: "âœ“ Ð“Ð¾Ñ‚Ð¾Ð²Ð¾ Ðº Ð·Ð°Ð¿ÑƒÑÐºÑƒ",
    NEEDS_INSTALLATION: "â—‹ Ð¢Ñ€ÐµÐ±ÑƒÐµÑ‚ÑÑ ÑƒÑÑ‚Ð°Ð½Ð¾Ð²ÐºÐ°",
    VERSION_DISPLAY_LABEL: "Ð’ÐµÑ€ÑÐ¸Ñ:",
    PLAY_ICON: "ðŸŽ®",
    CANCEL_ICON: "âŒ",
    SELECT_VERSION_ALERT: "Ð’Ñ‹Ð±ÐµÑ€Ð¸Ñ‚Ðµ Ð²ÐµÑ€ÑÐ¸ÑŽ Ð´Ð»Ñ Ð·Ð°Ð¿ÑƒÑÐºÐ°!",
    SERVER_MOTD: "Â§bÂ§lGerbarium Â§8| Â§aÐšÑ€Ð¸ÑÑ‚Ð°Ð»ÑŒÐ½Ð¾Ðµ Ð¾Ð±Ð½Ð¾Ð²Ð»ÐµÐ½Ð¸Ðµ!",
    PLAYER_ID_LABEL: "ID:",
    PLAYER_ID_UNKNOWN: "???",
    PLAYER_RANK_VIP: "VIP",
    PLAY_ARROW_ICON: "â–¶",
    TIME_REMAINING_LABEL: "ÐžÑÑ‚Ð°Ð»Ð¾ÑÑŒ:",
    MOCK_VERSIONS: [
      { id: "gerbarium-1.2", name: "Gerbarium v1.2" },
      { id: "fabric-1.21", name: "Fabric 1.21" },
      { id: "forge-1.20.1", name: "Forge 1.20.1" },
      { id: "vanilla-1.21.4", name: "Vanilla 1.21.4" },
      { id: "vanilla-42", name: "Ð¢Ð•Ð¡Ð¢ Ð Ð•Ð›Ð˜Ð—Ð 1.0.1" },
    ],
  },
  SETTINGS: {
    TITLE: "ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸",
    BACK_BUTTON: "â† ÐÐ°Ð·Ð°Ð´",
    LOGOUT_BUTTON: "Ð’Ñ‹Ð¹Ñ‚Ð¸",
    TABS: {
      general: "ÐžÐ‘Ð©Ð˜Ð•",
      java: "JAVA",
      profile: "ÐŸÐ ÐžÐ¤Ð˜Ð›Ð¬",
      support: "ÐŸÐžÐ”Ð”Ð•Ð Ð–ÐšÐ",
    },
    GENERAL: {
      TITLE: "ÐžÐ±Ñ‰Ð¸Ðµ Ð½Ð°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸",
      LANGUAGE_LABEL: "Ð¯Ð·Ñ‹Ðº",
      LANGUAGE_OPTIONS: [
        { value: "ru", label: "Ð ÑƒÑÑÐºÐ¸Ð¹" },
        { value: "en", label: "English" },
        { value: "es", label: "EspaÃ±ol" },
        { value: "fr", label: "FranÃ§ais" },
        { value: "de", label: "Deutsch" },
      ],
      CLOSE_ON_LAUNCH: "Ð—Ð°ÐºÑ€Ñ‹Ð²Ð°Ñ‚ÑŒ Ð»Ð°ÑƒÐ½Ñ‡ÐµÑ€ Ð¿Ñ€Ð¸ Ð·Ð°Ð¿ÑƒÑÐºÐµ Ð¸Ð³Ñ€Ñ‹",
      MINIMIZE_TO_TRAY: "Ð¡Ð²Ð¾Ñ€Ð°Ñ‡Ð¸Ð²Ð°Ñ‚ÑŒ Ð² Ñ‚Ñ€ÐµÐ¹",
      DISCORD_RPC: "ÐŸÐ¾ÐºÐ°Ð·Ñ‹Ð²Ð°Ñ‚ÑŒ ÑÑ‚Ð°Ñ‚ÑƒÑ Ð² Discord (RPC)",
    },
    JAVA: {
      TITLE: "ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸ Java",
      INSTALLED_VERSIONS: "Ð£ÑÑ‚Ð°Ð½Ð¾Ð²Ð»ÐµÐ½Ð½Ñ‹Ðµ Ð²ÐµÑ€ÑÐ¸Ð¸",
      PATH_LABEL: "ÐŸÑƒÑ‚ÑŒ Ðº Java",
      PATH_PLACEHOLDER: "C:/Program Files/Java/jdk/bin/java.exe",
      BROWSE_BUTTON: "Ð’Ñ‹Ð±Ñ€Ð°Ñ‚ÑŒ Ñ„Ð°Ð¹Ð»",
      RAM_LABEL: "Ð’Ñ‹Ð´ÐµÐ»ÐµÐ½Ð¸Ðµ ÐžÐ—Ð£:",
      JVM_ARGS_LABEL: "ÐÑ€Ð³ÑƒÐ¼ÐµÐ½Ñ‚Ñ‹ JVM",
      JVM_ARGS_PLACEHOLDER: "-XX:+UseG1GC -XX:MaxGCPauseMillis=50",
      JVM_ARGS_HELP: "Ð”Ð¾Ð¿Ð¾Ð»Ð½Ð¸Ñ‚ÐµÐ»ÑŒÐ½Ñ‹Ðµ Ð¿Ð°Ñ€Ð°Ð¼ÐµÑ‚Ñ€Ñ‹ Ð´Ð»Ñ Ð·Ð°Ð¿ÑƒÑÐºÐ° Java",
      DOWNLOAD_BUTTON: (v: number) => `Ð¡ÐºÐ°Ñ‡Ð°Ñ‚ÑŒ Java ${v}`,
      ALREADY_INSTALLED: (v: number) => `Java ${v} ÑƒÐ¶Ðµ ÑƒÑÑ‚Ð°Ð½Ð¾Ð²Ð»ÐµÐ½Ð°`,
    },
    PROFILE: {
      TITLE: "ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸ Ð¿Ñ€Ð¾Ñ„Ð¸Ð»Ñ",
      USERNAME_LABEL: "Ð˜Ð³Ñ€Ð¾Ðº",
      USERNAME_PLACEHOLDER: "Player",
      SKIN_URL_LABEL: "URL ÑÐºÐ¸Ð½Ð°",
      SKIN_URL_PLACEHOLDER: "https://example.com/skin.png",
      CAPE_URL_LABEL: "URL Ð¿Ð»Ð°Ñ‰Ð°",
      CAPE_URL_PLACEHOLDER: "https://example.com/cape.png",
      SKIN_PREVIEW_TITLE: "ÐŸÑ€ÐµÐ´Ð¿Ñ€Ð¾ÑÐ¼Ð¾Ñ‚Ñ€ ÑÐºÐ¸Ð½Ð°",
      SKIN_LOADING: "Ð—Ð°Ð³Ñ€ÑƒÐ·ÐºÐ°...",
      SKIN_NOT_SELECTED: "Ð¡ÐºÐ¸Ð½ Ð½Ðµ Ð²Ñ‹Ð±Ñ€Ð°Ð½",
    },
    ACTIONS: {
      SAVE_BUTTON: "Ð¡Ð¾Ñ…Ñ€Ð°Ð½Ð¸Ñ‚ÑŒ",
      SAVING: "Ð¡Ð¾Ñ…Ñ€Ð°Ð½ÐµÐ½Ð¸Ðµ...",
      RESET_BUTTON: "Ð¡Ð±Ñ€Ð¾ÑÐ¸Ñ‚ÑŒ",
    },
    DEBUG: {
      TITLE: "ÐžÑ‚Ð»Ð°Ð´ÐºÐ° Ð¸ ÐŸÐ¾Ð´Ð´ÐµÑ€Ð¶ÐºÐ°",
      HELP_TEXT:
        "Ð•ÑÐ»Ð¸ Ð²Ñ‹ ÑÑ‚Ð¾Ð»ÐºÐ½ÑƒÐ»Ð¸ÑÑŒ Ñ Ð¿Ñ€Ð¾Ð±Ð»ÐµÐ¼Ð¾Ð¹, Ð²Ñ‹Ð³Ñ€ÑƒÐ·Ð¸Ñ‚Ðµ Ð»Ð¾Ð³Ð¸ Ð¸ Ð¿Ñ€Ð¸ÐºÑ€ÐµÐ¿Ð¸Ñ‚Ðµ Ð¸Ñ… Ðº Ð±Ð°Ð³-Ñ€ÐµÐ¿Ð¾Ñ€Ñ‚Ñƒ Ð½Ð° GitHub.",
      EXPORT_BUTTON: "Ð¡Ð¾Ð¾Ð±Ñ‰Ð¸Ñ‚ÑŒ Ð¾Ð± Ð¾ÑˆÐ¸Ð±ÐºÐµ (Ð­ÐºÑÐ¿Ð¾Ñ€Ñ‚ Ð»Ð¾Ð³Ð¾Ð²)",
      EXPORTING: "ÐÑ€Ñ…Ð¸Ð²Ð°Ñ†Ð¸Ñ...",
      EXPORT_SUCCESS: (path: string) =>
        `Ð›Ð¾Ð³Ð¸ ÑƒÑÐ¿ÐµÑˆÐ½Ð¾ ÑÐ¾Ñ…Ñ€Ð°Ð½ÐµÐ½Ñ‹ Ð²:\n${path}\n\nÐžÑ‚ÐºÑ€Ð¾ÐµÑ‚ÑÑ Ð±Ñ€Ð°ÑƒÐ·ÐµÑ€ Ð´Ð»Ñ ÑÐ¾Ð·Ð´Ð°Ð½Ð¸Ñ Issue.`,
      EXPORT_ERROR: (err: string) => `ÐžÑˆÐ¸Ð±ÐºÐ° Ð¿Ñ€Ð¸ ÑÐ¾Ñ…Ñ€Ð°Ð½ÐµÐ½Ð¸Ð¸ Ð»Ð¾Ð³Ð¾Ð²:\n${err}`,
      EXPORT_UNEXPECTED_ERROR:
        "ÐŸÑ€Ð¾Ð¸Ð·Ð¾ÑˆÐ»Ð° Ð½ÐµÐ¿Ñ€ÐµÐ´Ð²Ð¸Ð´ÐµÐ½Ð½Ð°Ñ Ð¾ÑˆÐ¸Ð±ÐºÐ° Ð¿Ñ€Ð¸ ÑÐºÑÐ¿Ð¾Ñ€Ñ‚Ðµ Ð»Ð¾Ð³Ð¾Ð².",
      GITHUB_ISSUES_BUTTON: "Ð¡Ð²ÑÐ·Ð°Ñ‚ÑŒÑÑ Ñ‡ÐµÑ€ÐµÐ· GitHub Issues",
    },
    RESET_MODAL: {
      TITLE: "Ð¡Ð±Ñ€Ð¾Ñ Ð½Ð°ÑÑ‚Ñ€Ð¾ÐµÐº",
      TEXT: "Ð’Ñ‹ ÑƒÐ²ÐµÑ€ÐµÐ½Ñ‹, Ñ‡Ñ‚Ð¾ Ñ…Ð¾Ñ‚Ð¸Ñ‚Ðµ ÑÐ±Ñ€Ð¾ÑÐ¸Ñ‚ÑŒ Ð²ÑÐµ Ð½Ð°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸ Ð´Ð¾ Ð·Ð½Ð°Ñ‡ÐµÐ½Ð¸Ð¹ Ð¿Ð¾ ÑƒÐ¼Ð¾Ð»Ñ‡Ð°Ð½Ð¸ÑŽ? Ð­Ñ‚Ð¾ Ð´ÐµÐ¹ÑÑ‚Ð²Ð¸Ðµ Ð½ÐµÐ»ÑŒÐ·Ñ Ð¾Ñ‚Ð¼ÐµÐ½Ð¸Ñ‚ÑŒ.",
      CONFIRM: "Ð¡Ð±Ñ€Ð¾ÑÐ¸Ñ‚ÑŒ",
      CANCEL: "ÐžÑ‚Ð¼ÐµÐ½Ð°",
    },
  },
  UPDATE_SCREEN: {
    SEARCHING: "ÐŸÐ¾Ð¸ÑÐº Ð¾Ð±Ð½Ð¾Ð²Ð»ÐµÐ½Ð¸Ð¹...",
    FOUND: "ÐÐ°Ð¹Ð´ÐµÐ½Ð¾ Ð½Ð¾Ð²Ð¾Ðµ Ð¾Ð±Ð½Ð¾Ð²Ð»ÐµÐ½Ð¸Ðµ",
    NONE: "update-not-available",
    DOWNLOADED: "ÐžÐ±Ð½Ð¾Ð²Ð»ÐµÐ½Ð¸Ðµ ÑÐºÐ°Ñ‡Ð°Ð½Ð¾. ÐŸÐµÑ€ÐµÐ·Ð°Ð³Ñ€ÑƒÐ·ÐºÐ°...",
    ERROR_PREFIX: "ÐžÑˆÐ¸Ð±ÐºÐ°:",
    STARTING_LAUNCHER: "Ð—Ð°Ð¿ÑƒÑÐº Ð»Ð°ÑƒÐ½Ñ‡ÐµÑ€Ð°...",
    NOT_REQUIRED: "ÐžÐ±Ð½Ð¾Ð²Ð»ÐµÐ½Ð¸Ðµ Ð½Ðµ Ñ‚Ñ€ÐµÐ±ÑƒÐµÑ‚ÑÑ",
    COPYRIGHT: "Â© 2026 Gerbarium. Radmir Klimau.",
  },
  JAVA_STATUS: {
    EXTRACTING: "Ð Ð°ÑÐ¿Ð°ÐºÐ¾Ð²ÐºÐ°...",
    DOWNLOADING: "Ð—Ð°Ð³Ñ€ÑƒÐ·ÐºÐ°: ",
    SEARCHING: "ÐŸÐ¾Ð¸ÑÐº...",
    VERSION_FOUND: "ÐÐ°Ð¹Ð´ÐµÐ½Ð° Ð²ÐµÑ€ÑÐ¸Ñ: ",
    REMOVE_CONFIRM: (v: number) => `Ð£Ð´Ð°Ð»Ð¸Ñ‚ÑŒ Java ${v}?`,
  },
  DOWNLOAD: {
    IDLE: "ÐžÐ¶Ð¸Ð´Ð°Ð½Ð¸Ðµ",
    CHECKING: "ÐŸÑ€Ð¾Ð²ÐµÑ€ÐºÐ° Ñ„Ð°Ð¹Ð»Ð¾Ð²...",
    DOWNLOADING: "Ð—Ð°Ð³Ñ€ÑƒÐ·ÐºÐ°...",
    INSTALLING: "Ð£ÑÑ‚Ð°Ð½Ð¾Ð²ÐºÐ° Ð¼Ð¾Ð´Ð¾Ð²...",
    VERIFYING: "ÐŸÑ€Ð¾Ð²ÐµÑ€ÐºÐ° Ñ†ÐµÐ»Ð¾ÑÑ‚Ð½Ð¾ÑÑ‚Ð¸...",
    COMPLETED: "Ð—Ð°Ð²ÐµÑ€ÑˆÐµÐ½Ð¾",
    CANCELLED: "ÐžÑ‚Ð¼ÐµÐ½ÐµÐ½Ð¾",
    CALCULATING: "Ð Ð°ÑÑ‡ÐµÑ‚...",
  },
  NEWS: {
    CATEGORIES: {
      update: "ÐžÐ±Ð½Ð¾Ð²Ð»ÐµÐ½Ð¸Ðµ",
      event: "Ð¡Ð¾Ð±Ñ‹Ñ‚Ð¸Ðµ",
      community: "Ð¡Ð¾Ð¾Ð±Ñ‰ÐµÑÑ‚Ð²Ð¾",
      announcement: "ÐÐ½Ð¾Ð½Ñ",
    },
    MOCK: [
      {
        title: "ÐšÑ€Ð¸ÑÑ‚Ð°Ð»ÑŒÐ½Ñ‹Ðµ Ð¼Ð¾Ð±Ñ‹: ÐžÐ±Ð½Ð¾Ð²Ð»ÐµÐ½Ð¸Ðµ Ð“ÐµÑ€Ð±Ð°Ñ€Ð¸ÑƒÐ¼!",
        content:
          "ÐÐ¾Ð²Ð¾Ðµ ÐºÑ€ÑƒÐ¿Ð½Ð¾Ðµ Ð¾Ð±Ð½Ð¾Ð²Ð»ÐµÐ½Ð¸Ðµ Ð´Ð¾Ð±Ð°Ð²Ð»ÑÐµÑ‚ ÐºÑ€Ð¸ÑÑ‚Ð°Ð»ÑŒÐ½Ñ‹Ñ… Ð¼Ð¾Ð±Ð¾Ð², Ð½Ð¾Ð²Ñ‹Ðµ Ð±Ð¸Ð¾Ð¼Ñ‹ Ð¸ ÑƒÐ»ÑƒÑ‡ÑˆÐµÐ½Ð½ÑƒÑŽ ÑÐ¸ÑÑ‚ÐµÐ¼Ñƒ ÐºÑ€Ð°Ñ„Ñ‚Ð°. Ð˜ÑÑÐ»ÐµÐ´ÑƒÐ¹Ñ‚Ðµ Ð½Ð¾Ð²Ñ‹Ðµ Ð¸Ð·Ð¼ÐµÑ€ÐµÐ½Ð¸Ñ Ð¸ ÑÑ€Ð°Ð¶Ð°Ð¹Ñ‚ÐµÑÑŒ Ñ ÑÐ¿Ð¸Ñ‡ÐµÑÐºÐ¸Ð¼Ð¸ Ð±Ð¾ÑÑÐ°Ð¼Ð¸!",
      },
      {
        title: "ÐÐ¾Ð²Ð°Ñ ÑÐ¸ÑÑ‚ÐµÐ¼Ð° ÑÐºÐ¸Ð½Ð¾Ð²",
        content:
          "Ð¢ÐµÐ¿ÐµÑ€ÑŒ Ð²Ñ‹ Ð¼Ð¾Ð¶ÐµÑ‚Ðµ Ð·Ð°Ð³Ñ€ÑƒÐ¶Ð°Ñ‚ÑŒ ÑÐ¾Ð±ÑÑ‚Ð²ÐµÐ½Ð½Ñ‹Ðµ ÑÐºÐ¸Ð½Ñ‹ Ð¿Ñ€ÑÐ¼Ð¾ Ð² Ð»Ð°ÑƒÐ½Ñ‡ÐµÑ€Ðµ! ÐŸÐ¾Ð´Ð´ÐµÑ€Ð¶ÐºÐ° HD Ñ‚ÐµÐºÑÑ‚ÑƒÑ€ Ð¸ Ð¿Ð»Ð°Ñ‰ÐµÐ¹.",
      },
      {
        title: "Ð¢ÑƒÑ€Ð½Ð¸Ñ€ ÑÐ¾Ð¾Ð±Ñ‰ÐµÑÑ‚Ð²Ð°",
        content:
          "ÐŸÑ€Ð¸ÑÐ¾ÐµÐ´Ð¸Ð½ÑÐ¹Ñ‚ÐµÑÑŒ Ðº ÐµÐ¶ÐµÐ½ÐµÐ´ÐµÐ»ÑŒÐ½Ð¾Ð¼Ñƒ Ñ‚ÑƒÑ€Ð½Ð¸Ñ€Ñƒ! ÐŸÑ€Ð¸Ð·Ð¾Ð²Ð¾Ð¹ Ñ„Ð¾Ð½Ð´: 10,000 ÐºÑ€Ð¸ÑÑ‚Ð°Ð»Ð»Ð¾Ð². Ð ÐµÐ³Ð¸ÑÑ‚Ñ€Ð°Ñ†Ð¸Ñ Ð¾Ñ‚ÐºÑ€Ñ‹Ñ‚Ð° Ð´Ð¾ ÐºÐ¾Ð½Ñ†Ð° Ð½ÐµÐ´ÐµÐ»Ð¸.",
      },
    ],
  },
  ADMIN: {
    TITLE: "ÐŸÐ°Ð½ÐµÐ»ÑŒ Ð°Ð´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¾Ñ€Ð°",
    USERS_MANAGEMENT: "Ð£Ð¿Ñ€Ð°Ð²Ð»ÐµÐ½Ð¸Ðµ Ð¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»ÑÐ¼Ð¸",
    BACK_BUTTON: "â† ÐÐ°Ð·Ð°Ð´",
    REFRESH: "ÐžÐ±Ð½Ð¾Ð²Ð¸Ñ‚ÑŒ",
    LOADING: "Ð—Ð°Ð³Ñ€ÑƒÐ·ÐºÐ°...",
    SEARCH_PLACEHOLDER: "ÐŸÐ¾Ð¸ÑÐº Ð¿Ð¾ Ð½Ð¸ÐºÑƒ Ð¸Ð»Ð¸ Ð¿Ð¾Ñ‡Ñ‚Ðµ...",
    BANNED_BADGE: "Ð—ÐÐ‘ÐÐÐ•Ð",
    ID_LABEL: "ID:",
    ROLES_LABEL: "Ð Ð¾Ð»Ð¸:",
    REASON_LABEL: "ÐŸÑ€Ð¸Ñ‡Ð¸Ð½Ð°:",
    NO_USERS: "ÐŸÐ¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»Ð¸ Ð½Ðµ Ð½Ð°Ð¹Ð´ÐµÐ½Ñ‹.",
    BUTTONS: {
      EDIT_ROLES: "Ð˜Ð·Ð¼ÐµÐ½Ð¸Ñ‚ÑŒ Ñ€Ð¾Ð»Ð¸",
      UNBAN: "Ð Ð°Ð·Ð±Ð°Ð½Ð¸Ñ‚ÑŒ",
      BAN: "Ð—Ð°Ð±Ð°Ð½Ð¸Ñ‚ÑŒ",
    },
    PROMPTS: {
      BAN_REASON_TITLE: (username: string) => `Ð‘Ð»Ð¾ÐºÐ¸Ñ€Ð¾Ð²ÐºÐ° ${username}`,
      BAN_REASON_PLACEHOLDER: "ÐÐ°Ð¿Ñ€Ð¸Ð¼ÐµÑ€: ÐÐ°Ñ€ÑƒÑˆÐµÐ½Ð¸Ðµ Ð¿Ñ€Ð°Ð²Ð¸Ð»",
      UNBAN_CONFIRM_TITLE: (username: string) => `Ð Ð°Ð·Ð±Ð°Ð½Ð¸Ñ‚ÑŒ ${username}?`,
      EDIT_ROLES_TITLE: (username: string) => `Ð Ð¾Ð»Ð¸ Ð´Ð»Ñ ${username}`,
    },
    ROLES: {
      USER: "Ð˜Ð³Ñ€Ð¾Ðº",
      MODERATOR: "ÐœÐ¾Ð´ÐµÑ€Ð°Ñ‚Ð¾Ñ€",
      ADMIN: "ÐÐ´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¾Ñ€",
    },
    ERRORS: {
      FETCH_USERS: "ÐÐµ ÑƒÐ´Ð°Ð»Ð¾ÑÑŒ Ð·Ð°Ð³Ñ€ÑƒÐ·Ð¸Ñ‚ÑŒ ÑÐ¿Ð¸ÑÐ¾Ðº Ð¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»ÐµÐ¹",
      UPDATE_USER: "ÐÐµ ÑƒÐ´Ð°Ð»Ð¾ÑÑŒ Ð¾Ð±Ð½Ð¾Ð²Ð¸Ñ‚ÑŒ Ð´Ð°Ð½Ð½Ñ‹Ðµ Ð¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»Ñ",
    },
  },

  STORE_ERRORS: {
    SETTINGS_SAVE: "ÐÐµ ÑƒÐ´Ð°Ð»Ð¾ÑÑŒ ÑÐ¾Ñ…Ñ€Ð°Ð½Ð¸Ñ‚ÑŒ Ð½Ð°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸",
    SERVER_STATUS: "ÐÐµ ÑƒÐ´Ð°Ð»Ð¾ÑÑŒ Ð¿Ð¾Ð»ÑƒÑ‡Ð¸Ñ‚ÑŒ ÑÑ‚Ð°Ñ‚ÑƒÑ ÑÐµÑ€Ð²ÐµÑ€Ð°",
    NEWS_LOAD: "ÐÐµ ÑƒÐ´Ð°Ð»Ð¾ÑÑŒ Ð·Ð°Ð³Ñ€ÑƒÐ·Ð¸Ñ‚ÑŒ Ð½Ð¾Ð²Ð¾ÑÑ‚Ð¸",
    AUTH_LOGIN: "ÐžÑˆÐ¸Ð±ÐºÐ° Ð²Ñ…Ð¾Ð´Ð°",
    AUTH_REGISTER: "Registration error",
    AUTH_OFFLINE: "ÐžÑˆÐ¸Ð±ÐºÐ° Ð²Ñ…Ð¾Ð´Ð°",
    AUTH_EMPTY_FIELDS: "Ð’Ð²ÐµÐ´Ð¸Ñ‚Ðµ Ð»Ð¾Ð³Ð¸Ð½ Ð¸ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ",
    AUTH_EMPTY_USERNAME: "Ð’Ð²ÐµÐ´Ð¸Ñ‚Ðµ Ð¸Ð¼Ñ Ð¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»Ñ",
  },
} as const;

