name: API Integration Tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit

      - name: Run API Tests
        env:
          NODE_ENV: development
          API_BASE_URL: ${{ vars.API_BASE_URL }}
          BASE_PACKWIZ_URL: ${{ secrets.BASE_PACKWIZ_URL != '' && secrets.BASE_PACKWIZ_URL || vars.BASE_PACKWIZ_URL }}
          VITE_BASE_PACKWIZ_URL: ${{ secrets.VITE_BASE_PACKWIZ_URL != '' && secrets.VITE_BASE_PACKWIZ_URL || vars.VITE_BASE_PACKWIZ_URL }}
        run: npm run test:auth
